version: '3'
services:
  selenoid:
    networks:
      - selenoid
    image: aerokube/selenoid:latest-release
    volumes:
      - "$PWD:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD:/opt/selenoid/video"
      - "$PWD:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD
    command:
      [
        "-conf",
        "/etc/selenoid/browsers.json",
        "-video-output-dir",
        "/opt/selenoid/video",
        "-log-output-dir",
        "/opt/selenoid/logs",
        "-container-network",
        "selenoid"
      ]
    ports:
      - "4444:4444"
  automation:
    networks:
      selenoid: null
    environment:
      SELENIUM_HOST: selenoid
      SELENIUM_PORT: 4444
    image: test:test
    depends_on:
      - selenoid

networks:
  selenoid:
    external:
      name: selenoid # This assumes network is already created